import type { Metadata } from "next";
import { Geist, Geist_Mono, Ms_Madi } from "next/font/google"; // 1. Added Ms_Madi here
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. Initialize Ms Madi
const msMadi = Ms_Madi({
  weight: "400", // Ms Madi only supports weight 400
  subsets: ["latin"],
  variable: "--font-ms-madi", // Optional: allows you to use it in CSS via var(--font-ms-madi)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${msMadi.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}